config/routes.rb
Financials::Application.routes.draw do
	
  root :to => "pages#home"

  match '/about', :to => 'pages#about'

  resources :current_years
  resources :donations
  resources :pledges
  resources :users
  resources :budgets
  resources :weekdates
  resources :about

end

app/models/budget.rb
# == Schema Information
# Schema version: 20110223021550
#
# Table name: budgets
#
#  id          :integer         not null, primary key
#  description :string(50)
#  created_at  :datetime
#  updated_at  :datetime
#

class Budget < ActiveRecord::Base
  has_many :donations

  def select_list
	all_budgets = Budget.find(:all, :order => [:description])
	budget_array = Array[["Budget Items", nil]]
	all_budgets.each do |b|
	  budget_array.push Array[b.description, b.id ]
	end
	return budget_array
  end

  def fill_db
    data_file = File.open("/Users/Shared/NBC2010/Budget.tmp")
    data_records = data_file.readlines("\r")
    data_records.each do |r|
      obj = BudgetObj.new
      rec = r.chomp.split("\t")
      obj.create(rec)
      rec = Budget.new do |u|
        u.id = obj.id
        u.description = obj.description
      end
      rec.save
    end
    nil
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  # GET /budgets
  # GET /budgets.xml
  def index
    @budgets = Budget.order("description").page(params[:page]).per(16)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @budgets }
    end
  end

  # GET /budgets/1
  # GET /budgets/1.xml
  def show
    @budget = Budget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @budget }
    end
  end

  # GET /budgets/new
  # GET /budgets/new.xml
  def new
    @budget = Budget.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @budget }
    end
  end

  # GET /budgets/1/edit
  def edit
    @budget = Budget.find(params[:id])
  end

  # POST /budgets
  # POST /budgets.xml
  def create
    @budget = Budget.new(params[:budget])

    respond_to do |format|
      if @budget.save
        format.html { redirect_to(@budget, :notice => 'Budget was successfully created.') }
        format.xml  { render :xml => @budget, :status => :created, :location => @budget }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @budget.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /budgets/1
  # PUT /budgets/1.xml
  def update
    @budget = Budget.find(params[:id])

    respond_to do |format|
      if @budget.update_attributes(params[:budget])
        format.html { redirect_to(@budget, :notice => 'Budget was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @budget.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.xml
  def destroy
    @budget = Budget.find(params[:id])
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to(budgets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_for(@budget) do |f| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% @budget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<h1>Listing of Budget Items</h1>

<table border="1">
  <tr>
	<th>Key</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @budgets.each do |budget| %>
  <tr>
	<td><%= budget.id %></td>
    <td><%= budget.description %></td>
    <td><%= link_to 'Show', budget %></td>
    <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
    <td><%= link_to 'Destroy', budget, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= paginate @budgets %>

<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<h1>New budget</h1>

<%= render 'form' %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @budget.description %>
</p>


<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>