config/routes.rb
Financials::Application.routes.draw do
	
  root :to => "pages#home"

  match '/about', :to => 'pages#about'

  resources :current_years
  resources :donations
  resources :pledges
  resources :users
  resources :budgets
  resources :weekdates
  resources :about

end

app/models/current_year.rb
# == Schema Information
# Schema version: 20110223021550
#
# Table name: current_years
#
#  id         :integer         not null, primary key
#  year       :integer(4)      default(2010)
#  first_week :integer(1)      default(3)
#  created_at :datetime
#  updated_at :datetime
#

class CurrentYear < ActiveRecord::Base
  #attr_reader :year, :first_week
  #attr_writer :id, :year, :first_week

  def fill_db
    obj = CurrentYearObj.new
    obj.year = LASTYEAR
    obj.first_week = FIRSTSUNDAY
    puts obj.inspect
    rec = CurrentYear.new do |r|
      r.year = obj.year
      r.first_week = obj.first_week
    end
    rec.save
  end
end

app/controllers/current_years_controller.rb
class CurrentYearsController < ApplicationController
  # GET /current_years
  # GET /current_years.xml
  def index
    @current_years = CurrentYear.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @current_years }
    end
  end

  # GET /current_years/1
  # GET /current_years/1.xml
  def show
    @current_year = CurrentYear.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @current_year }
    end
  end

  # GET /current_years/new
  # GET /current_years/new.xml
  def new
    @current_year = CurrentYear.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @current_year }
    end
  end

  # GET /current_years/1/edit
  def edit
    @current_year = CurrentYear.find(params[:id])
  end

  # POST /current_years
  # POST /current_years.xml
  def create
    @current_year = CurrentYear.new(params[:current_year])

    respond_to do |format|
      if @current_year.save
        format.html { redirect_to(@current_year, :notice => 'Current year was successfully created.') }
        format.xml  { render :xml => @current_year, :status => :created, :location => @current_year }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @current_year.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /current_years/1
  # PUT /current_years/1.xml
  def update
    @current_year = CurrentYear.find(params[:id])

    respond_to do |format|
      if @current_year.update_attributes(params[:current_year])
        format.html { redirect_to(@current_year, :notice => 'Current year was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @current_year.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /current_years/1
  # DELETE /current_years/1.xml
  def destroy
    @current_year = CurrentYear.find(params[:id])
    @current_year.destroy

    respond_to do |format|
      format.html { redirect_to(current_years_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/current_years_helper.rb
module CurrentYearsHelper
end

app/views/current_years/_form.html.erb
<%= form_for(@current_year) do |f| %>
  <% if @current_year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_year.errors.count, "error") %> prohibited this current_year from being saved:</h2>

      <ul>
      <% @current_year.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :first_week %><br />
    <%= f.text_field :first_week %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/current_years/edit.html.erb
<h1>Editing current_year</h1>

<%= render 'form' %>

<%= link_to 'Show', @current_year %> |
<%= link_to 'Back', current_years_path %>

app/views/current_years/index.html.erb
<h1>Listing of Current Year</h1>

<table>
  <tr>
    <th>Year</th>
    <th>First sunday</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @current_years.each do |current_year| %>
  <tr>
    <td><%= current_year.year %></td>
    <td><%= current_year.first_week %></td>
    <td><%= link_to 'Show', current_year %></td>
    <td><%= link_to 'Edit', edit_current_year_path(current_year) %></td>
    <td><%= link_to 'Destroy', current_year, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Current year', new_current_year_path %>

app/views/current_years/new.html.erb
<h1>New current_year</h1>

<%= render 'form' %>

<%= link_to 'Back', current_years_path %>

app/views/current_years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @current_year.year %>
</p>

<p>
  <b>First sunday:</b>
  <%= @current_year.first_week %>
</p>


<%= link_to 'Edit', edit_current_year_path(@current_year) %> |
<%= link_to 'Back', current_years_path %>