config/routes.rb
Financials::Application.routes.draw do
	
  root :to => "pages#home"

  match '/about', :to => 'pages#about'

  resources :current_years
  resources :donations
  resources :pledges
  resources :users
  resources :budgets
  resources :weekdates
  resources :about

end

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <h2>NBC Financial Giving Records</h2>
  is a project to build an application to handle the financial giving database
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is based on the sample application used for for the tutorial.
</p>

app/views/pages/budget.html.erb
<h1>This is where the budgets will be listed</h1>
<p>Find me in app/views/pages/budget.html.erb</p>

app/views/pages/currentyear.html.erb
<h1>This is where the the current year will be listed</h1>
<p>Find me in app/views/pages/currentyear.html.erb</p>

app/views/pages/donation.html.erb
<h1>Listing donations</h1>

<table border="1">
  <tr>
    <th>Amount</th>
    <th>User</th>
    <th>Weekdate</th>
    <th>Budget</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donations.each do |donation| %>
  <tr>
    <td><%= donation.amount %></td>
    <td><%= donation.user_id %></td>
    <td><%= donation.weekdate_id %></td>
    <td><%= donation.budget_id %></td>
    <td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Donation', new_donation_path %>

app/views/pages/home.html.erb
<h1>Financials</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/feedback">Ruby on Rails Tutorial</a>
  sample application.
</p>
<p>
  <%= UserTex.new(-1).create_pdf_file %>
</p>
<p>
  This is where I will place the button to create the PDF file for all of the users.
</p>

app/views/pages/pledge.html.erb
<h1>This is where the pledges will be listed</h1>
<p>Find me in app/views/pages/pledge.html.erb</p>
<script type="text/javascript" src="/Users/robertsurtees/IdeaProjects/Financials/script/script02.js"></script>

<h1 id="helloMessage">
</h1>
</script>

app/views/pages/user.html.erb
<h1>Listing of users</h1>

<table border="1">
  <tr>
    <th>Surname</th>
    <th>Street</th>
    <th>po_box</th>
    <th>Town</th>
    <th>State</th>
    <th>Zip</th>
    <th>Email</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first %></td>
    <td><%= user.surname %></td>
    <td><%= user.street %></td>
    <td><%= user.po_box %></td>
    <td><%= user.town %></td>
    <td><%= user.state %></td>
    <td><%= user.zip %></td>
    <td><%= user.email %></td>
    <td><%= user.status %></td>
    <td><%= link_to 'Show', '/users/8001' %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/pages/weekdate.html.erb
<h1>This is where the week dates will be listed</h1>
<p>Find me in app/views/pages/weekdate.html.erb</p>