config/routes.rb
Financials::Application.routes.draw do
	
  root :to => "pages#home"

  match '/about', :to => 'pages#about'

  resources :current_years
  resources :donations
  resources :pledges
  resources :users
  resources :budgets
  resources :weekdates
  resources :about

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Home", root_path %></li>
      <li><a href="http://news.railstutorial.org/">Rails Tutorial News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("exterior1-small2.jpg", :alt => "Financial App", :class => "round" ) %>
  <%= link_to logo,  root_path %>  
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Current Year", current_years_path %></li>
      <li><%= link_to "Week Dates", weekdates_path %></li>
      <li><%= link_to "Budgets", budgets_path %></li>
      <li><%= link_to "Donations", donations_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Pledges", pledges_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
	<%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
	
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <!-- <h1><a href="#" id="alert" data-message="Thanks for testing!">Test Here</a></h1> -->
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>